{% set name = "felyxcontribs-metrics-ghrsst" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/felyx/felyxcontribs_metrics_ghrsst/-/archive/{{ version }}/felyxcontribs_metrics_ghrsst-{{ version }}.tar.gz
  sha256: 68791fba4dea34de94646e8aa338e1407c8c7eff0f2f572969ac3ab371cc602d

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
    - poetry-dynamic-versioning

  run:
    - python >={{ python_min }}
    - virtualenv >=20.13.3,<20.14
    
test:
  requires:
    - python {{ python_min }}
  imports:
    - felyxcontribs_metrics_ghrsst

about:
  home: https://gitlab.ifremer.fr/felyx/felyxcontribs_metrics_ghrsst
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: felyx extensions for ghrsst metrics.

extra:
  recipe-maintainers:
    - cso2943
    - criou-cg
    - erwanbodere
    - marie59
